name: Put Message

on:
  push:
    tags:
      - v1.*

jobs:
  message:
    runs-on: ubuntu-latest

    steps:
      - name: just echo a message
        run: echo "Hello SUSHI! v1*****"

      - name: watch sushi neta
        run: cat ./sushi/neta.md
