name: Release

on:
  release:
    path:
      - "sushi/**"
    types: published

jobs:
  message:
    runs-on: ubuntu-latest

    steps:
      - name: just echo a message
        run: echo "Publishe!!!!! SUSHI! v1*****"

      - name: watch neta
        run: cat neta.md
        working-directory: ./sushi
